name: Deploy on Tag

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.1.0'

      - name: Install dependencies
        run: npm install
  
      - name: Run Swagger
        run: npm run swagger
  
      - name: Build TypeScript
        run: tsc --build

      - name: Debug
        run: |
          ls -la

      - name: Copia archivos
        uses: appleboy/scp-action@v0.1.4
        with:
          host: "userprod-b1.deliver.ar"
          username: "ubuntu"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/ubuntu/nrelease"
